version: '3'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    hostname: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./test/uber-popug-realm.json:/opt/keycloak/data/import/main-realm.json:ro
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm"